import Head from 'next/head';
import Navbar from '../Navbar';

const Layout = ({ children }) => (
  <div>
    <Head>
      <title>Rick and Morty API</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className="Home">
      <Navbar />
      {children}
    </main>
  </div>
);

export default Layout;
